name: custom_tab_view
description: A custom tab view that safely handles dynamic tab rendering and avoids crashes from tab count mismatches.
version: 0.2.0
homepage: https://github.com/EdungDivinefavour/custom_tab_view
repository: https://github.com/EdungDivinefavour/custom_tab_view
issue_tracker: https://github.com/EdungDivinefavour/custom_tab_view/issues

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
